language: java

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew

git:
 submodules: false

after_success:
 - eval "$(ssh-agent -s)"
 - chmod 600 .travis/deploy_key.pem
 - ssh-add .travis/deploy_key.pem
 - git remote add deploy git@gitlab.com:DavisCSClub/website.git
 - git push deploy
