package org.dcsc.athena.objects;

public enum StatusType
{
	TUTOR_ADDED, TUTEE_ADDED, TUTOR_FOUND, TUTEE_FOUND, TUTOR_REMOVED, TUTEE_REMOVED, TUTOR_NOT_FOUND, TUTEE_NOT_FOUND, TUTOR_QUIT, TUTEE_QUIT, TUTOR_REGISTERED, DUPLICATE_LOGIN, ERROR, DUPE_ERROR
}